#!/bin/sh
# vim:ft=sh:noet:ts=3:sw=3:

if [ -n "$DEBUG" ] ; then
	set -x
fi

# Who am I?
_SELF="${0##*/}"

# used by _parse()
_ENV_FILE="@ENV_FILE@"

# stdin: heredoc text
_herecat() {
	local msg line lfcr
	lfcr="$(printf '%b' "\012\015")"
	while IFS="$lfcr" read -r line ; do
		msg="$msg$line$lfcr"
	done
	printf '%s' "$msg"
}

# [$1: EXIT CODE (0)]
_usage() { local ec="${1:-0}"
	_herecat << ENDUSAGETEXT
Usage: $_SELF [ARG...] [OPERATION]

  OPERATIONS:
   get*
   parse
   set [CONSOLE]

  -E --env-file FILE

  -h --help
  --usage
ENDUSAGETEXT
	exit "$ec"
}

#==============================================================================#
# DEPRECATED/REWRITE

## $1: base16 value
_hex2dec() {
	local __hex_value="$1"
	printf "%d" "0x$__hex_value"
}

## $1: base10 value
_dec2hex() {
	local __dec_value="$1"
	printf "%.2x" "$__dec_value"
}

## get the current color variables
_get() {
	local __i __c
	local __c0 __c1 __c2 __c3 __c4 __c5 __c6 __c7 __c8 __c9 __c10 __c11 __c12 __c13 __c14 __c15 # read values
	local __cl0 __cl1 __cl2 __cl3 __cl4 __cl5 __cl6 __cl7 __cl8 __cl9 __cl10 __cl11 __cl12 __cl13 __cl14 __cl15 # processed values

	for __c in "red" "grn" "blu"
	do
		IFS=',' read -r __c0 __c1 __c2 __c3 __c4 __c5 __c6 __c7 __c8 __c9 __c10 __c11 __c12 __c13 __c14 __c15 <"/sys/module/vt/parameters/default_$__c"
		__i=0
		while [ "$__i" -le 15 ]
		do
			eval "__cl$__i=\"\${__cl$__i:-\$(_dec2hex \${__c$__i})}\${__cl$__i:+,\$(_dec2hex \${__c$__i})}\""
			__i="$((__i + 1))"
		done
	done

	__i=0
	while [ "$__i" -le 15 ]
	do
		eval "echo COLOR_$__i=\"\${__cl$__i}\""
		__i="$((__i + 1))"
	done
}

## parse '$_ENV_FILE' into vtrgb
_parse() {
	local __i __j __c __rgb
	local __r __g __b # read values
	local __red __grn __blu # processed values
	local IFS

	if [ -f "$_ENV_FILE" ]
	then . "$_ENV_FILE"
	else echo "$_SELF: $_ENV_FILE: No such file" >&2
	fi

	COLOR_0="${COLOR_0:-00,00,00}"
	COLOR_1="${COLOR_1:-aa,00,00}"
	COLOR_2="${COLOR_2:-00,aa,00}"
	COLOR_3="${COLOR_3:-aa,55,00}"
	COLOR_4="${COLOR_4:-00,00,aa}"
	COLOR_5="${COLOR_5:-aa,00,aa}"
	COLOR_6="${COLOR_6:-00,aa,aa}"
	COLOR_7="${COLOR_7:-aa,aa,aa}"
	COLOR_8="${COLOR_8:-55,55,55}"
	COLOR_9="${COLOR_9:-ff,55,55}"
	COLOR_10="${COLOR_10:-55,ff,55}"
	COLOR_11="${COLOR_11:-ff,ff,55}"
	COLOR_12="${COLOR_12:-55,55,ff}"
	COLOR_13="${COLOR_13:-ff,55,ff}"
	COLOR_14="${COLOR_14:-55,ff,ff}"
	COLOR_15="${COLOR_15:-ff,ff,ff}"

	__i=0
	while [ "$__i" -le 15 ]
	do
		eval "__rgb=\"\$COLOR_$__i\""
		__j=0
		IFS=','; for __c in $__rgb
		do
			[ "$__j" -eq 0 ] && __red="${__red:-$(_hex2dec "$__c")}${__red:+,$(_hex2dec "$__c")}"
			[ "$__j" -eq 1 ] && __grn="${__grn:-$(_hex2dec "$__c")}${__grn:+,$(_hex2dec "$__c")}"
			[ "$__j" -eq 2 ] && __blu="${__blu:-$(_hex2dec "$__c")}${__blu:+,$(_hex2dec "$__c")}"
			__j="$((__j + 1))"
		done; unset -v IFS
		__i="$((__i + 1))"
	done
	printf "%s\n" "$__red" "$__grn" "$__blu"
}

## set the console colors
## requires root privileges (for setvtrgb)
## $1: target tty
_set() {
	local __target_tty="$1"
	_parse | setvtrgb -C"$__target_tty" -
}

# DEPRECATED/REWRITE END
#==============================================================================#


# TODO: move opt parsing to main()
# DEPRECATED: --env-file --help --usage
main() { local mode="$1" target_tty="${2:-$(tty)}"
	case "$mode" in
		'' | get ) _get ;;
		parse ) _parse ;;
		set )
			if ! _set "$target_tty" ; then
				echo "$_SELF: requires root privileges" >&2
				exit 4
			fi
		;;
		*)
			echo "$_SELF: invalid mode of operation -- '$mode'" >&2
			_usage 2
		;;
	esac
}

# parse the options
while true
do
	case "$1" in
	-E|--env-file) _ENV_FILE="$2"; shift 2 ;;
	-h|--help|--usage) _usage ;;
	--) shift; break ;;
	-*|--*) _usage 2 "$1" ;;
	*) break ;;
	esac
done

main "$@"
