#!/usr/bin/env bash
# vim:ft=bash:noet:ts=3:sw=3:

function build {
	add_binary setvtrgb
	add_runscript

	vconsole-colors -E /etc/vconsole.conf parse > "$BUILDROOT/consolecolors.vtrgb"
}

function help {
	local msg
	IFS='' read -r -d '' msg << ENDHELPMSG
This hook adds setvtrgb for console color setup during early userspace.
ENDHELPMSG
	printf '%s' "$msg"
}
