#!/usr/bin/env bash
# vim:ft=bash:noet:ts=3:sw=3:

function build {
	add_systemd_unit initrd-vconsole-colors.service
	add_symlink /usr/lib/systemd/system/initrd.target.wants/initrd-vconsole-colors.service ../initrd-vconsole-colors.service

	vconsole-colors -E /etc/vconsole.conf get > "$BUILDROOT/etc/vconsole.vtrgb"
}

function help {
	local msg
	IFS='' read -r -d '' msg << ENDHELPMSG
This hook adds setvtrgb and the associated service for console color setup during early userspace.
ENDHELPMSG
	printf '%s' "$msg"
}
